### PR TITLE
Listen to error events from Structs while parsing

### LINKED ISSUE #1: Fix method that Struct indicates an invalid input
Right now, if the input buffer to a Struct is too small for the parsing that gets done (cursor goes past the end of the buffer), it returns an 'error' event, but allows additional parsing calls to continue.

Additionally, the way the BTCNetwork object listens to those errors, it allows NodeJS to turn them into thrown Errors, and catches those in a try/catch block. This is not ideal, since there's no guarantee that the thrown Error came from the Struct child (might be a syntax error or critical NodeJS system error).

Instead, the Struct object should keep track of an internal state (failed or not), and don't keep processing once failed. And the BTCNetwork object should avoid try/catch, and instead listen for the error event, and mark the action as failed (stopping further processing). This could probably be best done using one of the helpers in the `async` module, to listen for an Error response and bail out of the chain then.

### PR DESCRIPTION
**Pull request by MidnightLightning**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Issues fixed by this | #1 |

Fixes #1 by using an internal `hasFailed` flag to tell what to return.
# Tasks
- [x] Write more test cases for valid examples
- [x] Changelog updated
- [x] Usage/Documentation updated
- [x] Tests pass
- [ ] ACK from other developers

### CODE REVIEW

**Comment by MidnightLightning** [comment]
@jprichardson @sidazhang Can I get an ACK on this change? I figure I'll merge this change in, and afterward pull `Struct` and `Message` off into their own library, as per discussion [here](https://github.com/cryptocoinjs/btc-transaction/pull/3#issuecomment-33763867)

**Comment by sidazhang** [comment]
@MidnightLightning I think this looks good.

Ack

I really like the new Struct where it doesn't require us to have an event Listern. Makes a lot of sense and makes using it a bit lighter.

Please merge. Once you pull them into their own lib, I will update btc-transaction accordingly.

**Comment by jprichardson** [comment]
Looks good. Merge when you're ready :)

**Comment by MidnightLightning** [comment]
New binary message library has been created as [`crypto-binary`](https://github.com/cryptocoinjs/crypto-binary)

**Pull request merged**
